Many improvements and fixes to debian packaging. Add example configs.

diff --git a/debian/wimaxrf.postinst b/debian/wimaxrf.postinst
--- a/debian/wimaxrf.postinst
+++ b/debian/wimaxrf.postinst
@@ -1,6 +1,3 @@
-#!/bin/sh
-VER=5.4
-RUBYVER=1.8
 #! /bin/sh
 #
 # see: dh_installdeb(1)
@@ -8,42 +5,41 @@ RUBYVER=1.8
 set -e
 
 # summary of how this script can be called:
-# * <postinst> configure' <most-recently-configured-version>
-# * <old-postinst> abort-upgrade' <new version>
-# * <conflictor's-postinst> abort-remove' in-favour' <package>
-# <new-version>
-# * <deconfigured's-postinst> abort-deconfigure' in-favour'
-# <failed-install-package> <version> removing'
-# <conflicting-package> <version>
+#        * <postinst> `configure' <most-recently-configured-version>
+#        * <old-postinst> `abort-upgrade' <new version>
+#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
+#          <new-version>
+#        * <postinst> `abort-remove'
+#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
+#          <failed-install-package> <version> `removing'
+#          <conflicting-package> <version>
 # for details, see http://www.debian.org/doc/debian-policy/ or
 # the debian-policy package
-#
+
+# source debconf library
+. /usr/share/debconf/confmodule
 
 VER=5.4
 
 case "$1" in
-    install|configure)
-    
-    #
-    # Source debconf library
-    #
-    . /usr/share/debconf/confmodule
-    cd /usr/share/omf-aggmgr-$VER/gems/1.8
-    echo "Installing gems for OMF to /usr/share/omf-aggmgr-$VER/gems/$RUBYVER" 
-    gem$RUBYVER install --no-ri --no-rdoc -l -f -i /usr/share/omf-aggmgr-$VER/gems/$RUBYVER /usr/share/omf-aggmgr-$VER/gems/$RUBYVER/cache/wimaxrf/*.gem
-    ;;
-    
+    configure)
+        cd "/usr/share/omf-aggmgr-${VER}"
+        echo "Installing gems for WimaxRF to ${PWD}/gems"
+        gem install -i ./gems --no-rdoc --no-ri -f -l omf-aggmgr/ogs_wimaxrf/gems/*.gem
+        ;;
+
     abort-upgrade|abort-remove|abort-deconfigure)
-    ;;
-    
+        ;;
+
     *)
-    echo "postinst called with unknown argument \$1'" >&2
-    exit 1
-    ;;
+        echo "postinst called with unknown argument \`$1'" >&2
+        exit 1
+        ;;
 esac
 
 # dh_installdeb will replace this with shell code automatically
 # generated by other debhelper scripts.
 
 #DEBHELPER#
+
 exit 0
